# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - asp-techno-deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      # Old Version　　　 (コメント：一時フォルダの容量制限エラーがでたため、下記ブロックで対応。deployできたら要削除）
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      # Revised Ver. 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
          # GitHub Actions 上の安全な一時ディレクトリを作成して pip キャッシュに使用
          mkdir -p $HOME/tmp-cache
          
          # 旧方式（tmp に依存）: pip install -r requirements.txt
          pip install --cache-dir=$HOME/tmp-cache -r requirements.txt

        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Zip artifact for deployment
        # run: zip release.zip ./* -r    (コメント：旧方式。Zipファイルを下記の通り限定することで軽量化⇒デプロイ確認でき次第、要削除）
        run: zip -r release.zip app requirements.txt -x "**/__pycache__/*" -x "**/.git/*" -x "venv/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'asp-techno-deploy'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A37CB9F51D47412BB5F093B51D3E7721 }}

      - name: Wait for deployment to stabilize
        run: sleep 30

      - name: Check deployment status
        run: |
          echo "Deployment completed. Please check the Azure portal for application status."
